name: gm-log-page
on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 将代码拉取到虚拟机
        uses: actions/checkout@v3

      - name: Install and Build # 安装依赖、打包，如果提前已打包好无需这一步
        run: |
          npm i -g pnpm
          pnpm install
          cd ./examples/react-project
          pnpm install
          pnpm run build

      - name: Deploy # 部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          publish_dir: ./examples/react-project/dist
          publish_branch: gh-pages
