name: indexDB-utils-page
on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']
jobs:
  auto-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # 将代码拉取到虚拟机
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        with:
          version: 9


      - name: Install  # 安装依赖、打包，如果提前已打包好无需这一步
        run: pnpm install

      - name: BUild packages
        run: pnpm build

      - name: cd Dir
        run: cd ./examples/react-project

      - name: install example packages
        run: pnpm install

      - name: build
        run: pnpm build
      
      - name: Deploy # 部署
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.ACTIONS_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
